IllegalCharInEntryType        = 'Line {0}: there is an illegal char "{1}" in Type!'
IllegalCharInEntryCitationKey = 'Line {0}: there is an illegal char "{1}" in Hash!'
BracketNotClosed              = 'Line {0}: the bracket of literature "{1}" is not closed!'
IllegalCharInTagName          = 'Line {0}: there is an illegal char "{1}" in Name!'
IllegalCharAfterEqualSign     = 'Line {0}: this is illegal char "{1}" after the equal sign!'
IllegalCharBetweenTags        = 'Line {0}: this is illegal char "{1}" between two properties!'