IllegalCharInType = 'Line {0}: there is an illegal char "{1}" in Type!'
IllegalCharInHash = 'Line {0}: there is an illegal char "{1}" in Hash!'
BracketNotClosed = 'Line {0}: the bracket of literature "{1}" is not closed!'
IllegalCharInName = 'Line {0}: there is an illegal char "{1}" in Name!'
IllegalCharAfterEqualSign = 'Line {0}: this is illegal char "{}" after the equal sign!'
IllegalCharBetweenProperties = 'Line {0}: this is illegal char "{}" between two properties!'